{% set dataset_name = "PARTICLEXS" %}
{% set version = "4.1.0" %}
{% set version_canonical_geant4 = "4.1" %}
{% set sha256 = "07ae1e048e9ac8e7f91f6696497dd55bd50ccc822d97af1a0b9e923212a6d7d1" %}
{% set env_var = "G4PARTICLEXSDATA" %}
{% set summary = "GEANT4 data files for evaluated particle cross-sections on natural composition of elements" %}

{% set name = "geant4-data-"+dataset_name.lower() %}
{% set install_dir = "share/Geant4/data/"+dataset_name+version_canonical_geant4 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://geant4-data.web.cern.ch/geant4-data/datasets/G4{{ dataset_name }}.{{ version_canonical_geant4 }}.tar.gz
  sha256: {{ sha256 }}
  folder: dataset

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/{{ install_dir }}
    - cp -r dataset/* ${PREFIX}/{{ install_dir }}
    - ${RECIPE_DIR}/create_activation_scripts.sh {{ name }} {{ env_var }} {{ install_dir }}

# Conda-forge is unable to build packages that have no dependencies so add
# `make` as a dummy build dependency
requirements:
  build:
    - make

test:
  commands:
    - '[ "${{ env_var }}" == "$CONDA_PREFIX/{{ install_dir }}" ]'

about:
  home: https://geant4.web.cern.ch/
  summary: {{ summary }}
  license: OTHER
  license_file: CREDIT

extra:
  recipe-maintainers:
    - chrisburr
    - tkittel
